SERVER_HOST = "127.0.0.1"
SERVER_PORT = 5555
CHAT_PORT = 5556
BUFFER_SIZE = 4096

WHITE = "white"
BLACK = "black"
SPECTATOR = "spectator"

WAITING = "waiting"
PLAYING = "playing"
FINISHED = "finished"

MSG_MOVE = "MOVE"
MSG_CHAT = "CHAT"
MSG_CREATE_GAME = "CREATE_GAME"
MSG_JOIN_GAME = "JOIN_GAME"
MSG_SPECTATE = "SPECTATE"
MSG_LEAVE = "LEAVE"
MSG_UPDATE = "UPDATE"
MSG_ERROR = "ERROR"
MSG_GAME_STARTED = "GAME_STARTED"
MSG_GAME_OVER = "GAME_OVER"
MSG_GET_GAMES = "GET_GAMES"
MSG_LOBBY_UPDATE = "LOBBY_UPDATE"

DEFAULT_TIME_CONTROL = 300
TIME_INCREMENT = 3